//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThuongMaiDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhanLoai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChiTietPhanLoai()
        {
            this.ChiTietKichCoes = new HashSet<ChiTietKichCo>();
        }
    
        public string MaCTPhanLoai { get; set; }
        public string TenPhanLoai { get; set; }
        public string MaSP { get; set; }
        public int Gia { get; set; }
        public bool Xoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietKichCo> ChiTietKichCoes { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
