//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThuongMaiDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.AnhSanPhams = new HashSet<AnhSanPham>();
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
            this.ChiTietPhanLoais = new HashSet<ChiTietPhanLoai>();
            this.ChiTietThongTinSPs = new HashSet<ChiTietThongTinSP>();
            this.DanhGias = new HashSet<DanhGia>();
        }
    
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public string MaCuaHang { get; set; }
        public string AnhBia { get; set; }
        public string MoTaSP { get; set; }
        public double DanhGia { get; set; }
        public int SoLuongDanhGia { get; set; }
        public double GiamGia { get; set; }
        public Nullable<System.DateTime> ThoiHan { get; set; }
        public string MaChiTietLoai { get; set; }
        public Nullable<bool> Xoa { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnhSanPham> AnhSanPhams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual ChiTietLoaiSanPham ChiTietLoaiSanPham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhanLoai> ChiTietPhanLoais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietThongTinSP> ChiTietThongTinSPs { get; set; }
        public virtual CuaHang CuaHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGia> DanhGias { get; set; }
    }
}
