//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThuongMaiDienTu.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ThuongMaiDienTuEntities : DbContext
    {
        public ThuongMaiDienTuEntities()
            : base("name=ThuongMaiDienTuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnhSanPham> AnhSanPhams { get; set; }
        public virtual DbSet<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual DbSet<ChiTietGioHang> ChiTietGioHangs { get; set; }
        public virtual DbSet<ChiTietKichCo> ChiTietKichCoes { get; set; }
        public virtual DbSet<ChiTietLoaiSanPham> ChiTietLoaiSanPhams { get; set; }
        public virtual DbSet<ChiTietPhanLoai> ChiTietPhanLoais { get; set; }
        public virtual DbSet<ChiTietThongTinSP> ChiTietThongTinSPs { get; set; }
        public virtual DbSet<CuaHang> CuaHangs { get; set; }
        public virtual DbSet<DanhGia> DanhGias { get; set; }
        public virtual DbSet<DonHang> DonHangs { get; set; }
        public virtual DbSet<KhuyenMai> KhuyenMais { get; set; }
        public virtual DbSet<LoaiSanPham> LoaiSanPhams { get; set; }
        public virtual DbSet<NguoiDung> NguoiDungs { get; set; }
        public virtual DbSet<Quan_Huyen> Quan_Huyen { get; set; }
        public virtual DbSet<SanPham> SanPhams { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<ThongTinLienHe> ThongTinLienHes { get; set; }
        public virtual DbSet<Tinh_ThanhPho> Tinh_ThanhPho { get; set; }
        public virtual DbSet<Xa_Phuong> Xa_Phuong { get; set; }
    
        public virtual int ThayDoiMatKhau(string id, string mK)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var mKParameter = mK != null ?
                new ObjectParameter("MK", mK) :
                new ObjectParameter("MK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThayDoiMatKhau", idParameter, mKParameter);
        }
    
        public virtual int ThemDanhGia(string id, Nullable<int> muc, string noidung, string maSP, Nullable<bool> an)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var mucParameter = muc.HasValue ?
                new ObjectParameter("muc", muc) :
                new ObjectParameter("muc", typeof(int));
    
            var noidungParameter = noidung != null ?
                new ObjectParameter("noidung", noidung) :
                new ObjectParameter("noidung", typeof(string));
    
            var maSPParameter = maSP != null ?
                new ObjectParameter("maSP", maSP) :
                new ObjectParameter("maSP", typeof(string));
    
            var anParameter = an.HasValue ?
                new ObjectParameter("an", an) :
                new ObjectParameter("an", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemDanhGia", idParameter, mucParameter, noidungParameter, maSPParameter, anParameter);
        }
    
        public virtual int ThemSPVaoGioHang(string iD, string maCTKichCo, Nullable<int> soLuong)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            var maCTKichCoParameter = maCTKichCo != null ?
                new ObjectParameter("MaCTKichCo", maCTKichCo) :
                new ObjectParameter("MaCTKichCo", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemSPVaoGioHang", iDParameter, maCTKichCoParameter, soLuongParameter);
        }
    
        public virtual int TinhGiaTriDonHangTruocKhuyenMai(string madh, ObjectParameter gt)
        {
            var madhParameter = madh != null ?
                new ObjectParameter("Madh", madh) :
                new ObjectParameter("Madh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TinhGiaTriDonHangTruocKhuyenMai", madhParameter, gt);
        }
    
        public virtual int XoaChiTietGioHangDuaVaoCTDonHang(string id, string maCTKC, Nullable<int> sl)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var maCTKCParameter = maCTKC != null ?
                new ObjectParameter("maCTKC", maCTKC) :
                new ObjectParameter("maCTKC", typeof(string));
    
            var slParameter = sl.HasValue ?
                new ObjectParameter("sl", sl) :
                new ObjectParameter("sl", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaChiTietGioHangDuaVaoCTDonHang", idParameter, maCTKCParameter, slParameter);
        }
    
        public virtual int XoaSanPham(string maSP)
        {
            var maSPParameter = maSP != null ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaSanPham", maSPParameter);
        }
    }
}
